version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: reminder-app
    container_name: reminder-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - reminder-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: reminder-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - reminder-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: reminder-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: reminder_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: reminder_user
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - reminder-network

networks:
  reminder-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

